project:
  type: website
  resources:
    - "files/"

website:
  title: "Robert Kubinec Homepage"
  reader-mode: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "My novel *The Bayesian Hitman* is now available on [Amazon](https://www.amazon.com/Bayesian-Hitman-Robert-M-Kubinec/dp/B0D6M4WNRZ/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=)."
    type: dark
    position: below-navbar
  sidebar:
    style: "docked"
    contents:
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
      - text: "Blog"
        href: index.qmd
      - text: "Research"
        file: research/index.qmd
      - consulting.qmd
      - ordbetareg.qmd
      - text: "`idealstan`"
        href: https://saudiwin.github.io/idealstan/
      - text: "CoronaNet"
        href: https://coronanet-project.org/
  google-analytics: 
    tracking-id: "G-BHP1PJ9LEX"
  navbar:
    logo: files/img/formal_cropped_profile_cirle.png
    right:
      - icon: github
        href: https://github.com/saudiwin
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/rmkubinec.bsky.social
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
format:
  html:
    theme: lux
    css: styles.css

editor: visual

