project:
  type: website
  resources:
    - "files/"

website:
  title: "Homepage"
  reader-mode: true
  open-graph: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Read my latest on 5 lessons from political science to help rebuild Syria in [*The Conversation*](https://theconversation.com/as-syria-ponders-a-democratic-future-5-lessons-from-the-arab-spring-246203)."
    type: dark
    position: below-navbar
  sidebar:
    style: "docked"
    contents:
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
      - text: "Blog"
        href: index.qmd
      - text: "Research"
        file: research/index.qmd
      - consulting.qmd
      - text: "Ordered Beta Regression"
        href: https://saudiwin.github.io/ordbetareg_pack/
      - text: "`idealstan`"
        href: https://saudiwin.github.io/idealstan/
      - text: "CoronaNet"
        href: https://coronanet-project.org/
  google-analytics: 
    tracking-id: "G-BHP1PJ9LEX"
  navbar:
    right:
      - icon: github
        href: https://github.com/saudiwin
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/rmkubinec.bsky.social
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
format:
  html:
    theme: lux
    css: styles.css

editor: visual

