project:
  type: website
  resources:
    - "files/"

website:
  title: "Robert Kubinec"
  sidebar:
    style: "docked"
    contents:
      - text: "Punk Rock Poli Sci"
        href: index.qmd
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
      - text: "Research"
        file: research/index.qmd
      - consulting.qmd
      - ordbetareg.qmd
      - idealstan.qmd
  google-analytics: 
    tracking-id: "G-BHP1PJ9LEX"
  navbar:
    right:
      - icon: github
        href: https://github.com/saudiwin
      - icon: twitter
        href: https://twitter.com/rmkubinec
format:
  html:
    theme: lux
    css: styles.css

editor: visual

