project:
  type: website
  resources:
    - "files/"

website:
  title: "Robert Kubinec"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "My novel *The Bayesian Hitman* is now available on [Amazon](https://www.amazon.com/Bayesian-Hitman-Robert-M-Kubinec/dp/B0D6M4WNRZ/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=)."
    type: dark
    position: below-navbar
  sidebar:
    style: "docked"
    contents:
      - text: "Punk Rock Poli Sci"
        href: index.qmd
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
      - text: "Research"
        file: research/index.qmd
      - consulting.qmd
      - ordbetareg.qmd
      - idealstan.qmd
  google-analytics: 
    tracking-id: "G-BHP1PJ9LEX"
  navbar:
    right:
      - icon: github
        href: https://github.com/saudiwin
      - icon: twitter
        href: https://twitter.com/rmkubinec
      - text: CV
        href: files/Robert_Kubinec_CV_full.pdf
format:
  html:
    theme: lux
    css: styles.css

editor: visual

