---
title: "Research"
listing:
  - id: books
    contents: "books/*/index.qmd"
    sort: "date desc"
    template: ../html/research/listing.ejs
    categories: true
  - id: articles
    contents: "articles/*/index.qmd"
    sort: "date desc"
    template: ../html/research/listing.ejs
    categories: true
  # - id: working-papers
  #   contents: "working-papers/*/index.qmd"
  #   sort: "date desc"
  #   template: ../html/research/listing.ejs
  #   categories: true
  # - id: reviews
  #   contents: "reviews/*/index.qmd"
  #   sort: "date desc"
  #   template: ../html/research/listing.ejs
  #- id: essays
  #  contents: "essays/*/index.qmd"
  #  sort: "date desc"
  #  template: ../html/research/listing.ejs
page-layout: full
include-back-link: false
toc-location: left
---

On this page you can see a list of my articles, books, and other published works (see table of contents on the left) along with associated code and datasets. You can view my [CV here](../files/Robert_Kubinec_CV_full.pdf). My research has focused on the following questions that span the political economy of development, data science, causal inference and Middle East politics:

-   How do businesses influence politics in countries with serious issues of corruption and regulatory mismanagement?

-   How do businesspeople become successful entrepreneurs in countries where personal and political relationships are necessary to grow their firm?

-   How can we use Bayesian statistical methods to make robust inferences with complex datasets?

-   How can scientists develop robust measures of concepts they care about and make credible causal inferences that take into account diverse forms of data and evidence?

Often these questions overlap, such as when I use new statistical tools I develop to study corruption in the MENA region and elsewhere. My R packages, [ordbetareg](https://saudiwin.github.io/ordbetareg_pack/) and [idealstan](https://saudiwin.github.io/idealstan/), both came out of my research in studying online experiments and legislature behavior, and have also been used in other studies to date. I am both a skeptic of data science & AI and a developer of data-scientific methods because I see great promise *and* peril in quantification.

Please see below for a list of recent publications, though please note that not all of the publications on my CV are listed here as of yet.

## Books

::: {#books}
:::

## Journal articles

::: {#articles}
:::

## Working papers

::: {#working-papers}
:::

## Essays and Op-eds

::: {#essays}
:::

## Open Peer Reviews

::: {#reviews}
:::
